name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: |
        mkdir -p build
        cd build
        cmake ..
        make update -j
    - name: build
      run: |
        cd build
        make -j
        make install
    - name: check
      run: |
        cd build
        make check -j
    - name: package
      run: |
        cd build
        make package
        rm -rf out/_CPack_Packages
    - name: archive results
      uses: actions/upload-artifact@v1
      with:
        name: packages
        path: build/out
